### ISSUE TITLE
Update react/http to v1

### ISSUE THREAD

**Issue by WyriHaximus** [WyriHaximus/reactphp-http-contextual-middleware-runner#22]
This package needs update to react/http v1 and have a new major release tag.

Check list for that:

1. Update the dependency
2. Update the code based on migration guide: https://github.com/reactphp/http/releases/tag/v1.0.0
3. Make sure tests don't fail, not that this project hasn't been update in a while so if some jobs or Travis fail that is fine
4. Create PR

**Comment by mookman288** [comment]
In order to proceed with this PR, react-http-middleware-runner needs to be tagged and pushed on packagist with the PR that was released today, otherwise have a conflict on versioning:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for wyrihaximus/react-http-middleware-runner ^1.0 -> satisfiable by wyrihaximus/react-http-middleware-runner[1.0.0].
    - wyrihaximus/react-http-middleware-runner 1.0.0 requires react/http ^0.8.0 -> satisfiable by react/http[v0.8.0, v0.8.1, v0.8.2, v0.8.3, v0.8.4, v0.8.5, v0.8.6, v0.8.7] but these conflict with your requirements or minimum-stability.
```

As an alternative, I can switch to dev-master, but that might not be appropriate.

**Comment by WyriHaximus** [comment]
Will tag a new version in a minute :+1:

**Comment by WyriHaximus** [comment]
Ok tagged the release, it should be resolve through composer in a few minutes.
